services:
  pgdatabase:
    # image: postgres:13
    image: postgres:13 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - 5432:5432
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network

  # ingestion:
  #   build:
  #     - 'context:/home/sen-cloudangles/Desktop/Dev/pers/dezoomcamp/module1/'
  #     - dockerfile: Dockerfile
  #   networks:
  #     - pg-network


networks:
  pg-network:
    # driver: bridge
  
